version: 0.1

phases:
  pre_build:
    commands:
      - npm install npm -g
      - npm install
      - npm run test
  build:
    commands:
      - npm run dev
artifacts:
  files:
    - index.html
    - favicon.ico
    - MattHainesResume.pdf
    - styles/main.css
    - images/*
    - dist/main.js
